distribution: c_param
run_toy: false
order_to_match: 2
name: 2d
mstar: 1

init_random: true
init_g_matrix_path: c_param_1_1d
init_theta_path: c_param_1_1d
learn_theta: true

ratio_loss: false
weighted_mse_loss: true # must be false for toy

use_logbins: false

# these params only used for toy
n_bins: 200
t_min: 0
t_max: 10


epochs: 100000
batch_size: 320 # must be 320 for data
lr: 0.001
seed: 42
weight_decay: 0.01
m: 2
n: 10
device: cuda
