distribution: theta_toy
run_toy: true
order_to_match: 2
name: test
mstar: 1

init_random: true
init_g_matrix_path: none
init_theta_path: none
learn_theta: true
reroll_initialization: false

ratio_loss: false
weighted_mse_loss: false # must be false for toy
use_logbins: false

# these params only used for toy
n_bins: 200
t_min: 0
t_max: 10


epochs: 10000
batch_size: 512 # must be 320 for data
lr: 0.001
seed: 42
weight_decay: 0.01
m: 2
n: 3
device: cuda
